template: 'facelessuser:master-labels:labels.yml:master'

# Wildcard labels

brace_expansion: true
extended_glob: true
minus_negate: false

rules:
  - labels: ['C: infrastructure']
    patterns: ['*|@(requirements|.github)/**|!*.md']

  - labels: ['C: source']
    patterns: ['pyspelling/**']

  - labels: ['C: docs']
    patterns: ['*.md|docs/**']

  - labels: ['C: tests']
    patterns: ['tests/**']

  - labels: ['C: plugins']
    patterns: ['pyspelling/@(filters|flow_control)/**|pyspelling/plugin.py']

  - labels: ['C: wildcard-flow-control']
    patterns: ['@(tests|pyspelling)/**/?(test_)wildcard.py']

  - labels: ['C: context-filter']
    patterns: ['@(tests|pyspelling)/**/?(test_)context.py']

  - labels: ['C: cpp-filter']
    patterns: ['@(tests|pyspelling)/**/?(test_)cpp.py']

  - labels: ['C: html-filter']
    patterns: ['@(tests|pyspelling)/**/?(test_)html.py']

  - labels: ['C: javascript-filter']
    patterns: ['@(tests|pyspelling)/**/?(test_)javascript.py']

  - labels: ['C: markdown-filter']
    patterns: ['@(tests|pyspelling)/**/?(test_)markdown.py']

  - labels: ['C: odf-filter']
    patterns: ['@(tests|pyspelling)/**/?(test_)odf.py']

  - labels: ['C: ooxml-filter']
    patterns: ['@(tests|pyspelling)/**/?(test_)ooxml.py']

  - labels: ['C: python-filter']
    patterns: ['@(tests|pyspelling)/**/?(test_)python.py']

  - labels: ['C: stylesheets-filter']
    patterns: ['@(tests|pyspelling)/**/?(test_)stylesheets.py']

  - labels: ['C: text-filter']
    patterns: ['@(tests|pyspelling)/**/?(test_)text.py']

  - labels: ['C: url-filter']
    patterns: ['@(tests|pyspelling)/**/?(test_)url.py']

  - labels: ['C: xml-filter']
    patterns: ['@(tests|pyspelling)/**/?(test_)xml.py']

# Label management

labels:
- name: 'C: plugins'
  renamed: plugins
  color: subcategory
  description: Related to general plugin code.

- name: 'C: wildcard-flow-control'
  renamed: wildcard-flow-control
  color: pending
  description: Wildcard flow control.

- name: 'C: context-filter'
  renamed: context-filter
  color: subcategory
  description: Related to the context filter.

- name: 'C: cpp-filter'
  renamed: cpp-filter
  color: subcategory
  description: Related to the cpp filter.

- name: 'C: html-filter'
  renamed: html-filter
  color: subcategory
  description: Related to the html filter.

- name: 'C: javascript-filter'
  renamed: javascript-filter
  color: subcategory
  description: Related to the javascript filter.

- name: 'C: markdown-filter'
  renamed: markdown-filter
  color: subcategory
  description: Related to the markdown filter.

- name: 'C: odf-filter'
  renamed: odf-filter
  color: subcategory
  description: Related to the odf filter.

- name: 'C: ooxml-filter'
  renamed: ooxml-filter
  color: subcategory
  description: Related to the ooxml filter.

- name: 'C: python-filter'
  renamed: python-filter
  color: subcategory
  description: Related to the python filter.

- name: 'C: stylesheets-filter'
  renamed: stylesheets-filter
  color: subcategory
  description: Related to the stylesheets filter.

- name: 'C: text-filter'
  renamed: text-filter
  color: subcategory
  description: Related to the text filter.

- name: 'C: url-filter'
  renamed: url-filter
  color: subcategory
  description: Related to the url filter.

- name: 'C: xml-filter'
  renamed: xml-filter
  color: subcategory
  description: Related to the xml filter.
